const errors = require('./errors')

module.exports = exports = function generateC(hyperschema) {
  return {
    header: generateHeader(hyperschema),
    source: generateSource(hyperschema)
  }
}

exports.toCName = toCName
exports.structName = structName
exports.enumConstName = enumConstName
exports.generateCMake = generateCMake
exports.resolveBase = resolveBase
exports.typeInfo = typeInfo
exports.fixedSize = fixedSize
exports.targetName = targetName

const TYPES = new Map([
  ['bool', { cType: 'bool', compactSuffix: 'bool', signed: false }],
  ['uint', { cType: 'uint64_t', compactSuffix: 'uint', signed: false }],
  ['int', { cType: 'int64_t', compactSuffix: 'int', signed: true }],
  ['uint8', { cType: 'uint8_t', compactSuffix: 'uint8', signed: false }],
  ['uint16', { cType: 'uint16_t', compactSuffix: 'uint16', signed: false }],
  ['uint32', { cType: 'uint32_t', compactSuffix: 'uint32', signed: false }],
  ['uint64', { cType: 'uint64_t', compactSuffix: 'uint64', signed: false }],
  ['int8', { cType: 'int8_t', compactSuffix: 'int8', signed: true }],
  ['int16', { cType: 'int16_t', compactSuffix: 'int16', signed: true }],
  ['int32', { cType: 'int32_t', compactSuffix: 'int32', signed: true }],
  ['int64', { cType: 'int64_t', compactSuffix: 'int64', signed: true }],
  ['fixed32', { cType: 'uint8_t', compactSuffix: 'fixed32', signed: false }],
  ['fixed64', { cType: 'uint8_t', compactSuffix: 'fixed64', signed: false }],
  ['buffer', { cType: 'uint8_t', compactSuffix: 'uint8array', signed: false, isBuffer: true }],
  ['string', { cType: 'utf8_string_view_t', compactSuffix: 'utf8', signed: false, isString: true }],
  ['json', { cType: 'utf8_string_view_t', compactSuffix: 'utf8', signed: false, isString: true }],
  ['float32', { cType: 'float', compactSuffix: 'float32', signed: false }],
  ['float64', { cType: 'double', compactSuffix: 'float64', signed: false }],
  ['uint24', { cType: 'uint32_t', compactSuffix: 'uint24', signed: false }],
  ['uint40', { cType: 'uint64_t', compactSuffix: 'uint40', signed: false }],
  ['uint48', { cType: 'uint64_t', compactSuffix: 'uint48', signed: false }],
  ['uint56', { cType: 'uint64_t', compactSuffix: 'uint56', signed: false }],
  ['int24', { cType: 'int32_t', compactSuffix: 'int24', signed: true }],
  ['int40', { cType: 'int64_t', compactSuffix: 'int40', signed: true }],
  ['int48', { cType: 'int64_t', compactSuffix: 'int48', signed: true }],
  ['int56', { cType: 'int64_t', compactSuffix: 'int56', signed: true }]
])

function typeInfo(typeName) {
  const info = TYPES.get(typeName)
  if (!info) {
    throw errors.UNSUPPORTED_TYPE(
      `Unsupported field type "${typeName}", supported: ${[...TYPES.keys()].join(', ')}`
    )
  }
  return info
}

// All top-level types in schema declaration order. The header/source loops
// walk this and dispatch by kind, so enums (and later aliases, versioned types)
// land in the same order they were declared — dependencies before dependents.
function getTopLevelTypes(hyperschema) {
  const types = []
  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    types.push(hyperschema.resolve(fqn))
  }
  return types
}

function getStructs(hyperschema) {
  return getTopLevelTypes(hyperschema).filter((t) => t.isStruct)
}

function getNamespaces(structs) {
  return [...new Set(structs.map((t) => toCName(t.namespace)))]
}

// Returns 'schema' for empty schemas so toCode() succeeds on minimal fixtures.
// generateCMake throws separately — a CMake target with no source files is nonsense.
function targetName(hyperschema) {
  const namespaces = getNamespaces(getStructs(hyperschema))
  if (!namespaces.length) return 'schema'
  return namespaces.join('_') + '_schema'
}

function generateCMake(hyperschema) {
  const structs = getStructs(hyperschema)
  if (!structs.length) {
    throw errors.EMPTY_SCHEMA('Schema has no structs, cannot derive CMake target name')
  }
  const target = targetName(hyperschema)

  return [
    '# This file is autogenerated by hyperschema-c',
    '# !!DO NOT EDIT!!',
    '#',
    '# Expects: a `compact` CMake target provided by the consumer.',
    '',
    'cmake_minimum_required(VERSION 4.0)',
    '',
    `project(${target} C)`,
    '',
    `add_library(${target} OBJECT ${target}.c)`,
    '',
    'set_target_properties(',
    `  ${target}`,
    '  PROPERTIES',
    '  C_STANDARD 99',
    ')',
    '',
    `target_include_directories(${target} PUBLIC .)`,
    '',
    `target_link_libraries(${target} PUBLIC compact)`,
    ''
  ].join('\n')
}

function generateHeader(hyperschema) {
  const types = getTopLevelTypes(hyperschema)
  const structs = types.filter((t) => t.isStruct)
  const namespaces = getNamespaces(structs)
  const nsPrefix = namespaces.length ? namespaces.map((ns) => ns.toUpperCase()).join('_') + '_' : ''
  const guard = nsPrefix + 'SCHEMA_H'

  const needsBool = structs.some((t) =>
    t.fields.some((f) => !f.required || resolveBase(f.type).name === 'bool')
  )

  const lines = [
    '// This file is autogenerated by hyperschema-c',
    '// !!DO NOT EDIT!!',
    `// Schema Version: ${hyperschema.version}`,
    '',
    `#ifndef ${guard}`,
    `#define ${guard}`,
    '',
    '#include <compact.h>'
  ]

  if (needsBool) lines.push('#include <stdbool.h>')

  for (const type of types) {
    if (type.isEnum) lines.push('', ...generateEnumDecl(type))
    else if (type.isStruct) lines.push('', ...generateStructDecl(type))
  }

  lines.push('', `#endif // ${guard}`, '')
  return lines.join('\n')
}

function generateSource(hyperschema) {
  const types = getTopLevelTypes(hyperschema)
  const structs = types.filter((t) => t.isStruct)
  const target = targetName(hyperschema)

  const lines = [
    '// This file is autogenerated by hyperschema-c',
    '// !!DO NOT EDIT!!',
    '',
    `#include "${target}.h"`
  ]

  if (structs.some((t) => structNeedsDestroy(t))) lines.push('#include <stdlib.h>')

  for (const type of types) {
    if (type.isStruct) lines.push('', ...generateStructImpl(type))
  }

  lines.push('')
  return lines.join('\n')
}

function toCName(name) {
  // hyphens to underscores, camelCase to snake_case
  return name
    .replace(/-/g, '_')
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .toLowerCase()
}

function structName(type) {
  return toCName(type.namespace) + '_' + toCName(type.name)
}

// An enum is a uint on the wire (index + offset) with a named C type.
function enumTypeName(type) {
  return structName(type) + '_t'
}

function enumConstName(type, key) {
  return (structName(type) + '_' + toCName(key)).toUpperCase()
}

function generateEnumDecl(type) {
  const lines = [`// ${type.fqn} enum`, `typedef enum ${structName(type)}_e {`]
  for (let i = 0; i < type.enum.length; i++) {
    const comma = i < type.enum.length - 1 ? ',' : ''
    lines.push(`  ${enumConstName(type, type.enum[i].key)} = ${i + type.offset}${comma}`)
  }
  lines.push(`} ${enumTypeName(type)};`)
  return lines
}

function generateStructDecl(type) {
  const name = structName(type)
  const lines = []

  lines.push(`// ${type.fqn}`)
  lines.push(`typedef struct ${name}_s {`)

  if (type.fields.length === 0) {
    lines.push(`  char _unused; // C99 does not allow empty structs`)
  } else {
    for (const field of type.fields) {
      const cField = toCName(field.name)
      const base = resolveBase(field.type)
      if (!field.required && !isFlagBool(field)) lines.push(`  bool has_${cField};`)
      if (field.array) {
        if (base.isStruct) {
          lines.push(`  ${structName(base)}_t *${cField}; /* array */`)
        } else {
          const { cType } = typeInfo(base.name)
          const n = fixedSize(base.name)
          if (n) {
            lines.push(`  uint8_t (*${cField})[${n}]; /* array of fixed${n} */`)
          } else {
            lines.push(`  ${cType} *${cField}; /* array */`)
          }
        }
        lines.push(`  size_t ${cField}_len;`)
      } else if (base.isStruct) {
        lines.push(`  ${structName(base)}_t ${cField};`)
      } else if (base.isEnum) {
        lines.push(`  ${enumTypeName(base)} ${cField};`)
      } else {
        const { cType, isBuffer, isString } = typeInfo(base.name)
        const n = fixedSize(base.name)
        if (isBuffer) {
          lines.push(`  ${cType} *${cField}; /* borrows from decode buffer */`)
          lines.push(`  size_t ${cField}_len;`)
        } else if (isString) {
          lines.push(`  ${cType} ${cField}; /* borrows from decode buffer */`)
        } else if (n) {
          lines.push(`  ${cType} ${cField}[${n}];`)
        } else {
          lines.push(`  ${cType} ${cField};`)
        }
      }
    }
  }

  lines.push(`} ${name}_t;`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_preencode (compact_state_t *state, const ${name}_t *value);`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_encode (compact_state_t *state, const ${name}_t *value);`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_decode (compact_state_t *state, ${name}_t *result);`)

  lines.push('')
  lines.push(`void`)
  lines.push(`${name}_destroy (${name}_t *result);`)

  return lines
}

function generateStructImpl(type) {
  const name = structName(type)
  const optionals = type.fields.filter((f) => !f.required)
  const flagsPos = type.flagsPosition // -1 = no flags (all required, compact)
  const lines = []

  lines.push(...generatePreencode(name, type.fields, flagsPos, optionals))
  lines.push('')
  lines.push(...generateEncode(name, type.fields, flagsPos, optionals))
  lines.push('')
  lines.push(...generateDecode(name, type.fields, flagsPos, optionals, structNeedsDestroy(type)))

  lines.push('')
  lines.push(...generateDestroy(name, type.fields))

  return lines
}

function generatePreencode(name, fields, flagsPos, optionals) {
  const lines = []
  lines.push(`int`)
  lines.push(`${name}_preencode (compact_state_t *state, const ${name}_t *value)`)
  lines.push(`{`)
  if (fields.length > 0) lines.push(`  int err;`)

  for (let i = 0; i < fields.length; i++) {
    const field = fields[i]
    const cField = toCName(field.name)

    if (i === flagsPos) {
      lines.push(`  uint64_t flags = 0;`)
      for (let j = 0; j < optionals.length; j++) lines.push(flagBit(optionals[j], j))
      lines.push(`  if ((err = compact_preencode_uint(state, flags)) < 0) return err;`)
    }

    if (isFlagBool(field)) continue // value lives in the flags bit, no separate byte

    const base = resolveBase(field.type)
    if (field.array) {
      const elemCall = arrayElemPreencode(base, cField, 'value')
      if (field.required) {
        lines.push(
          `  if ((err = compact_preencode_uint(state, value->${cField}_len)) < 0) return err;`
        )
        lines.push(`  for (size_t _i = 0; _i < value->${cField}_len; _i++) {`)
        lines.push(`    if ((err = ${elemCall}) < 0) return err;`)
        lines.push(`  }`)
      } else {
        lines.push(`  if (value->has_${cField}) {`)
        lines.push(
          `    if ((err = compact_preencode_uint(state, value->${cField}_len)) < 0) return err;`
        )
        lines.push(`    for (size_t _i = 0; _i < value->${cField}_len; _i++) {`)
        lines.push(`      if ((err = ${elemCall}) < 0) return err;`)
        lines.push(`    }`)
        lines.push(`  }`)
      }
    } else if (base.isStruct) {
      const innerName = structName(base)
      if (!field.framed) {
        const call = `${innerName}_preencode(state, &value->${cField})`
        if (field.required) {
          lines.push(`  if ((err = ${call}) < 0) return err;`)
        } else {
          lines.push(`  if (value->has_${cField}) {`)
          lines.push(`    if ((err = ${call}) < 0) return err;`)
          lines.push(`  }`)
        }
      } else {
        if (field.required) {
          lines.push(`  { compact_state_t _inner = {0};`)
          lines.push(
            `    if ((err = ${innerName}_preencode(&_inner, &value->${cField})) < 0) return err;`
          )
          lines.push(
            `    if ((err = compact_preencode_uint8array(state, NULL, _inner.end)) < 0) return err; }`
          )
        } else {
          lines.push(`  if (value->has_${cField}) {`)
          lines.push(`    compact_state_t _inner = {0};`)
          lines.push(
            `    if ((err = ${innerName}_preencode(&_inner, &value->${cField})) < 0) return err;`
          )
          lines.push(
            `    if ((err = compact_preencode_uint8array(state, NULL, _inner.end)) < 0) return err;`
          )
          lines.push(`  }`)
        }
      }
    } else if (base.isEnum) {
      if (field.required) {
        lines.push(
          `  if ((err = compact_preencode_uint(state, (uint64_t)value->${cField})) < 0) return err;`
        )
      } else {
        lines.push(`  if (value->has_${cField}) {`)
        lines.push(
          `    if ((err = compact_preencode_uint(state, (uint64_t)value->${cField})) < 0) return err;`
        )
        lines.push(`  }`)
      }
    } else {
      const { compactSuffix, isBuffer } = typeInfo(base.name)
      const encodeArgs = isBuffer ? `value->${cField}, value->${cField}_len` : `value->${cField}`
      if (field.required) {
        lines.push(
          `  if ((err = compact_preencode_${compactSuffix}(state, ${encodeArgs})) < 0) return err;`
        )
      } else {
        lines.push(`  if (value->has_${cField}) {`)
        lines.push(
          `    if ((err = compact_preencode_${compactSuffix}(state, ${encodeArgs})) < 0) return err;`
        )
        lines.push(`  }`)
      }
    }
  }

  lines.push(`  return 0;`)
  lines.push(`}`)
  return lines
}

function generateEncode(name, fields, flagsPos, optionals) {
  const lines = []
  lines.push(`int`)
  lines.push(`${name}_encode (compact_state_t *state, const ${name}_t *value)`)
  lines.push(`{`)
  if (fields.length > 0) lines.push(`  int err;`)

  for (let i = 0; i < fields.length; i++) {
    const field = fields[i]
    const cField = toCName(field.name)

    if (i === flagsPos) {
      lines.push(`  uint64_t flags = 0;`)
      for (let j = 0; j < optionals.length; j++) lines.push(flagBit(optionals[j], j))
      lines.push(`  if ((err = compact_encode_uint(state, flags)) < 0) return err;`)
    }

    if (isFlagBool(field)) continue // value lives in the flags bit, no separate byte

    const base = resolveBase(field.type)
    if (field.array) {
      const elemCall = arrayElemEncode(base, cField, 'value')
      if (field.required) {
        lines.push(
          `  if ((err = compact_encode_uint(state, value->${cField}_len)) < 0) return err;`
        )
        lines.push(`  for (size_t _i = 0; _i < value->${cField}_len; _i++) {`)
        lines.push(`    if ((err = ${elemCall}) < 0) return err;`)
        lines.push(`  }`)
      } else {
        lines.push(`  if (value->has_${cField}) {`)
        lines.push(
          `    if ((err = compact_encode_uint(state, value->${cField}_len)) < 0) return err;`
        )
        lines.push(`    for (size_t _i = 0; _i < value->${cField}_len; _i++) {`)
        lines.push(`      if ((err = ${elemCall}) < 0) return err;`)
        lines.push(`    }`)
        lines.push(`  }`)
      }
    } else if (base.isStruct) {
      const innerName = structName(base)
      if (!field.framed) {
        const call = `${innerName}_encode(state, &value->${cField})`
        if (field.required) {
          lines.push(`  if ((err = ${call}) < 0) return err;`)
        } else {
          lines.push(`  if (value->has_${cField}) {`)
          lines.push(`    if ((err = ${call}) < 0) return err;`)
          lines.push(`  }`)
        }
      } else {
        if (field.required) {
          lines.push(`  { compact_state_t _inner = {0};`)
          lines.push(
            `    if ((err = ${innerName}_preencode(&_inner, &value->${cField})) < 0) return err;`
          )
          lines.push(
            `    if ((err = compact_encode_uint(state, (uint64_t)_inner.end)) < 0) return err;`
          )
          lines.push(
            `    if ((err = ${innerName}_encode(state, &value->${cField})) < 0) return err; }`
          )
        } else {
          lines.push(`  if (value->has_${cField}) {`)
          lines.push(`    compact_state_t _inner = {0};`)
          lines.push(
            `    if ((err = ${innerName}_preencode(&_inner, &value->${cField})) < 0) return err;`
          )
          lines.push(
            `    if ((err = compact_encode_uint(state, (uint64_t)_inner.end)) < 0) return err;`
          )
          lines.push(
            `    if ((err = ${innerName}_encode(state, &value->${cField})) < 0) return err;`
          )
          lines.push(`  }`)
        }
      }
    } else if (base.isEnum) {
      if (field.required) {
        lines.push(
          `  if ((err = compact_encode_uint(state, (uint64_t)value->${cField})) < 0) return err;`
        )
      } else {
        lines.push(`  if (value->has_${cField}) {`)
        lines.push(
          `    if ((err = compact_encode_uint(state, (uint64_t)value->${cField})) < 0) return err;`
        )
        lines.push(`  }`)
      }
    } else {
      const { compactSuffix, isBuffer } = typeInfo(base.name)
      const encodeArgs = isBuffer ? `value->${cField}, value->${cField}_len` : `value->${cField}`
      if (field.required) {
        lines.push(
          `  if ((err = compact_encode_${compactSuffix}(state, ${encodeArgs})) < 0) return err;`
        )
      } else {
        lines.push(`  if (value->has_${cField}) {`)
        lines.push(
          `    if ((err = compact_encode_${compactSuffix}(state, ${encodeArgs})) < 0) return err;`
        )
        lines.push(`  }`)
      }
    }
  }

  lines.push(`  return 0;`)
  lines.push(`}`)
  return lines
}

function generateDecode(name, fields, flagsPos, optionals, needsDestroy = false) {
  const hasDirectArrays = fields.some((f) => f.array)
  const lines = []
  lines.push(`int`)
  lines.push(`${name}_decode (compact_state_t *state, ${name}_t *result)`)
  lines.push(`{`)
  if (fields.length > 0) lines.push(`  int err;`)
  if (hasDirectArrays) lines.push(`  uint64_t _count;`)

  const onErr = needsDestroy ? 'goto fail' : 'return err'
  const onNull = needsDestroy ? '{ err = -1; goto fail; }' : 'return -1;'

  for (let i = 0; i < fields.length; i++) {
    const field = fields[i]
    const cField = toCName(field.name)

    if (i === flagsPos) {
      lines.push(`  uint64_t flags = 0;`)
      lines.push(`  if ((err = compact_decode_uint(state, &flags)) < 0) ${onErr};`)
      for (let j = 0; j < optionals.length; j++) {
        const opt = optionals[j]
        const target = isFlagBool(opt) ? toCName(opt.name) : `has_${toCName(opt.name)}`
        lines.push(`  result->${target} = (flags & ((uint64_t)1 << ${j})) != 0;`)
      }
    }

    if (isFlagBool(field)) continue // value already read from the flags bit

    const base = resolveBase(field.type)
    if (field.array) {
      const elemCall = arrayElemDecode(base, cField, 'result')
      if (field.required) {
        lines.push(`  if ((err = compact_decode_uint(state, &_count)) < 0) ${onErr};`)
        lines.push(`  result->${cField} = calloc(_count, sizeof(*result->${cField}));`)
        lines.push(`  if (result->${cField} == NULL && _count > 0) ${onNull}`)
        lines.push(`  result->${cField}_len = (size_t)_count;`)
        lines.push(`  for (size_t _i = 0; _i < (size_t)_count; _i++) {`)
        lines.push(`    if ((err = ${elemCall}) < 0) ${onErr};`)
        lines.push(`  }`)
      } else {
        lines.push(`  if (result->has_${cField}) {`)
        lines.push(`    if ((err = compact_decode_uint(state, &_count)) < 0) ${onErr};`)
        lines.push(`    result->${cField} = calloc(_count, sizeof(*result->${cField}));`)
        lines.push(`    if (result->${cField} == NULL && _count > 0) ${onNull}`)
        lines.push(`    result->${cField}_len = (size_t)_count;`)
        lines.push(`    for (size_t _i = 0; _i < (size_t)_count; _i++) {`)
        lines.push(`      if ((err = ${elemCall}) < 0) ${onErr};`)
        lines.push(`    }`)
        lines.push(`  }`)
      }
    } else if (base.isStruct) {
      const innerName = structName(base)
      if (!field.framed) {
        const call = `${innerName}_decode(state, &result->${cField})`
        if (field.required) {
          lines.push(`  if ((err = ${call}) < 0) ${onErr};`)
        } else {
          lines.push(`  if (result->has_${cField}) {`)
          lines.push(`    if ((err = ${call}) < 0) ${onErr};`)
          lines.push(`  }`)
        }
      } else {
        if (field.required) {
          lines.push(`  { uint8_t *_blob; size_t _blob_len;`)
          lines.push(
            `    if ((err = compact_decode_uint8array(state, &_blob, &_blob_len)) < 0) ${onErr};`
          )
          lines.push(`    compact_state_t _inner = {0, _blob_len, _blob};`)
          lines.push(
            `    if ((err = ${innerName}_decode(&_inner, &result->${cField})) < 0) ${onErr}; }`
          )
        } else {
          lines.push(`  if (result->has_${cField}) {`)
          lines.push(`    uint8_t *_blob; size_t _blob_len;`)
          lines.push(
            `    if ((err = compact_decode_uint8array(state, &_blob, &_blob_len)) < 0) ${onErr};`
          )
          lines.push(`    compact_state_t _inner = {0, _blob_len, _blob};`)
          lines.push(
            `    if ((err = ${innerName}_decode(&_inner, &result->${cField})) < 0) ${onErr};`
          )
          lines.push(`  }`)
        }
      }
    } else if (base.isEnum) {
      const cast = `result->${cField} = (${enumTypeName(base)})_e;`
      if (field.required) {
        lines.push(`  { uint64_t _e;`)
        lines.push(`    if ((err = compact_decode_uint(state, &_e)) < 0) ${onErr};`)
        lines.push(`    ${cast} }`)
      } else {
        lines.push(`  if (result->has_${cField}) {`)
        lines.push(`    uint64_t _e;`)
        lines.push(`    if ((err = compact_decode_uint(state, &_e)) < 0) ${onErr};`)
        lines.push(`    ${cast}`)
        lines.push(`  }`)
      }
    } else {
      const fieldTypeName = base.name
      const { compactSuffix, isBuffer } = typeInfo(fieldTypeName)
      const decodeArgs = isBuffer
        ? `&result->${cField}, &result->${cField}_len`
        : `${fixedSize(fieldTypeName) ? '' : '&'}result->${cField}`
      if (field.required) {
        lines.push(
          `  if ((err = compact_decode_${compactSuffix}(state, ${decodeArgs})) < 0) ${onErr};`
        )
      } else {
        lines.push(`  if (result->has_${cField}) {`)
        lines.push(
          `    if ((err = compact_decode_${compactSuffix}(state, ${decodeArgs})) < 0) ${onErr};`
        )
        lines.push(`  }`)
      }
    }
  }

  lines.push(`  return 0;`)
  if (needsDestroy) {
    lines.push(`fail:`)
    lines.push(`  ${name}_destroy(result);`)
    lines.push(`  return err;`)
  }
  lines.push(`}`)
  return lines
}

function structNeedsDestroy(type, visited = new Set()) {
  if (visited.has(type)) return false
  visited.add(type)
  return type.fields.some((f) => {
    if (f.array) return true
    const base = resolveBase(f.type)
    return base.isStruct && structNeedsDestroy(base, visited)
  })
}

function generateDestroy(name, fields) {
  const lines = []
  lines.push(`void`)
  lines.push(`${name}_destroy (${name}_t *result)`)
  lines.push(`{`)
  for (const field of fields) {
    const cField = toCName(field.name)
    const base = resolveBase(field.type)
    if (field.array) {
      if (base.isStruct) {
        lines.push(`  for (size_t _i = 0; _i < result->${cField}_len; _i++) {`)
        lines.push(`    ${structName(base)}_destroy(&result->${cField}[_i]);`)
        lines.push(`  }`)
      }
      lines.push(`  free(result->${cField});`)
      lines.push(`  result->${cField} = NULL;`)
    } else if (base.isStruct) {
      lines.push(`  ${structName(base)}_destroy(&result->${cField});`)
    }
  }
  lines.push(`}`)
  return lines
}

function arrayElemPreencode(base, cField, ptr) {
  if (base.isStruct) return `${structName(base)}_preencode(state, &${ptr}->${cField}[_i])`
  const { compactSuffix } = typeInfo(base.name)
  return `compact_preencode_${compactSuffix}(state, ${ptr}->${cField}[_i])`
}

function arrayElemEncode(base, cField, ptr) {
  if (base.isStruct) return `${structName(base)}_encode(state, &${ptr}->${cField}[_i])`
  const { compactSuffix } = typeInfo(base.name)
  return `compact_encode_${compactSuffix}(state, ${ptr}->${cField}[_i])`
}

function arrayElemDecode(base, cField, ptr) {
  if (base.isStruct) return `${structName(base)}_decode(state, &${ptr}->${cField}[_i])`
  const { compactSuffix } = typeInfo(base.name)
  const n = fixedSize(base.name)
  const ref = n ? '' : '&'
  return `compact_decode_${compactSuffix}(state, ${ref}${ptr}->${cField}[_i])`
}

function fixedSize(typeName) {
  const m = typeName.match(/^fixed(\d+)$/)
  return m ? parseInt(m[1], 10) : 0
}

// hyperschema encodes a bool as a single flag bit whose value IS the bool —
// there is no separate byte and no presence bit. Arrays of bool are ordinary
// elements, so this only applies to scalar bool fields.
function isFlagBool(field) {
  return !field.array && resolveBase(field.type).name === 'bool'
}

// Condition that sets field `j`'s flag bit: a flag-bool contributes its value,
// every other optional contributes its presence.
function flagBit(field, j) {
  const cField = toCName(field.name)
  const cond = isFlagBool(field) ? `value->${cField}` : `value->has_${cField}`
  return `  if (${cond}) flags |= ((uint64_t)1 << ${j});`
}

function resolveBase(type) {
  if (!type) {
    throw errors.UNRESOLVED_TYPE('Field has no resolved type, schema may be incomplete')
  }
  if (type.isAlias) return resolveBase(type.type)
  return type
}
