'use strict'

module.exports = function generateC (hyperschema) {
  const lines = [
    '// This file is autogenerated by hyperschema-c',
    '// !!DO NOT EDIT!!',
    `// Schema Version: ${hyperschema.version}`,
    '',
    '#ifndef SCHEMA_H',
    '#define SCHEMA_H',
    '',
    '#include <compact.h>',
    '#include <stdbool.h>',
  ]

  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    const type = hyperschema.resolve(fqn)
    if (type.isStruct) lines.push('', ...generateStruct(type))
  }

  lines.push('', '#endif // SCHEMA_H', '')
  return lines.join('\n')
}

function toCName (name) {
  // hyphens to underscores, camelCase to snake_case
  return name
    .replace(/-/g, '_')
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .toLowerCase()
}

function structName (type) {
  return toCName(type.namespace) + '_' + toCName(type.name)
}

function generateStruct (type) {
  assertUintOnly(type)

  const name = structName(type)
  const hasOptionals = type.fields.some((f) => !f.required)
  const lines = []

  lines.push(`// ${type.fqn}`)
  lines.push(`typedef struct ${name}_s {`)

  // Track optional index for has_ ordering
  let optIndex = 0
  for (const field of type.fields) {
    const cField = toCName(field.name)
    if (!field.required) {
      lines.push(`  bool has_${cField};`)
      optIndex++
    }
    lines.push(`  uintmax_t ${cField};`)
  }

  lines.push(`} ${name}_t;`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_preencode (compact_state_t *state, const ${name}_t *value);`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_encode (compact_state_t *state, const ${name}_t *value);`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_decode (compact_state_t *state, ${name}_t *result);`)

  return lines
}

function assertUintOnly (type) {
  for (const field of type.fields) {
    const base = resolveBase(field.type)
    if (base.name !== 'uint') {
      throw new Error(
        `hyperschema-c: unsupported field type "${base.name}" on ${type.fqn}.${field.name} — only uint is supported in v1`
      )
    }
  }
}

function resolveBase (type) {
  if (type.isAlias) return resolveBase(type.type)
  return type
}
