'use strict'

module.exports = function generateC (hyperschema) {
  return {
    header: generateHeader(hyperschema),
    source: generateSource(hyperschema),
  }
}

function generateHeader (hyperschema) {
  const lines = [
    '// This file is autogenerated by hyperschema-c',
    '// !!DO NOT EDIT!!',
    `// Schema Version: ${hyperschema.version}`,
    '',
    '#ifndef SCHEMA_H',
    '#define SCHEMA_H',
    '',
    '#include <compact.h>',
    '#include <stdbool.h>',
  ]

  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    const type = hyperschema.resolve(fqn)
    if (type.isStruct) lines.push('', ...generateStructDecl(type))
  }

  lines.push('', '#endif // SCHEMA_H', '')
  return lines.join('\n')
}

function generateSource (hyperschema) {
  const lines = [
    '// This file is autogenerated by hyperschema-c',
    '// !!DO NOT EDIT!!',
    '',
    '#include "schema.h"',
  ]

  for (let i = 0; i < hyperschema.schema.length; i++) {
    const fqn = hyperschema.typesByPosition.get(i)
    const type = hyperschema.resolve(fqn)
    if (type.isStruct) lines.push('', ...generateStructImpl(type))
  }

  lines.push('')
  return lines.join('\n')
}

function toCName (name) {
  // hyphens to underscores, camelCase to snake_case
  return name
    .replace(/-/g, '_')
    .replace(/([a-z])([A-Z])/g, '$1_$2')
    .toLowerCase()
}

function structName (type) {
  return toCName(type.namespace) + '_' + toCName(type.name)
}

function generateStructDecl (type) {
  assertUintOnly(type)

  const name = structName(type)
  const lines = []

  lines.push(`// ${type.fqn}`)
  lines.push(`typedef struct ${name}_s {`)

  for (const field of type.fields) {
    const cField = toCName(field.name)
    if (!field.required) lines.push(`  bool has_${cField};`)
    lines.push(`  uintmax_t ${cField};`)
  }

  lines.push(`} ${name}_t;`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_preencode (compact_state_t *state, const ${name}_t *value);`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_encode (compact_state_t *state, const ${name}_t *value);`)
  lines.push('')
  lines.push(`int`)
  lines.push(`${name}_decode (compact_state_t *state, ${name}_t *result);`)

  return lines
}

function generateStructImpl (type) {
  assertUintOnly(type)

  const name = structName(type)
  const optionals = type.fields.filter((f) => !f.required)
  const flagsPos = type.flagsPosition // -1 = no flags (all required, compact)
  const lines = []

  lines.push(...generatePreencode(name, type.fields, flagsPos, optionals))
  lines.push('')
  lines.push(...generateEncode(name, type.fields, flagsPos, optionals))
  lines.push('')
  lines.push(...generateDecode(name, type.fields, flagsPos, optionals))

  return lines
}

function generatePreencode (name, fields, flagsPos, optionals) {
  const lines = []
  lines.push(`int`)
  lines.push(`${name}_preencode (compact_state_t *state, const ${name}_t *value)`)
  lines.push(`{`)
  lines.push(`  int err;`)

  for (let i = 0; i < fields.length; i++) {
    const field = fields[i]
    const cField = toCName(field.name)

    if (i === flagsPos) {
      lines.push(`  uintmax_t flags = 0;`)
      for (let j = 0; j < optionals.length; j++) {
        lines.push(`  if (value->has_${toCName(optionals[j].name)}) flags |= (1u << ${j});`)
      }
      lines.push(`  if ((err = compact_preencode_uint(state, flags)) < 0) return err;`)
    }

    if (field.required) {
      lines.push(`  if ((err = compact_preencode_uint(state, value->${cField})) < 0) return err;`)
    } else {
      lines.push(`  if (value->has_${cField}) {`)
      lines.push(`    if ((err = compact_preencode_uint(state, value->${cField})) < 0) return err;`)
      lines.push(`  }`)
    }
  }

  lines.push(`  return 0;`)
  lines.push(`}`)
  return lines
}

function generateEncode (name, fields, flagsPos, optionals) {
  const lines = []
  lines.push(`int`)
  lines.push(`${name}_encode (compact_state_t *state, const ${name}_t *value)`)
  lines.push(`{`)
  lines.push(`  int err;`)

  for (let i = 0; i < fields.length; i++) {
    const field = fields[i]
    const cField = toCName(field.name)

    if (i === flagsPos) {
      lines.push(`  uintmax_t flags = 0;`)
      for (let j = 0; j < optionals.length; j++) {
        lines.push(`  if (value->has_${toCName(optionals[j].name)}) flags |= (1u << ${j});`)
      }
      lines.push(`  if ((err = compact_encode_uint(state, flags)) < 0) return err;`)
    }

    if (field.required) {
      lines.push(`  if ((err = compact_encode_uint(state, value->${cField})) < 0) return err;`)
    } else {
      lines.push(`  if (value->has_${cField}) {`)
      lines.push(`    if ((err = compact_encode_uint(state, value->${cField})) < 0) return err;`)
      lines.push(`  }`)
    }
  }

  lines.push(`  return 0;`)
  lines.push(`}`)
  return lines
}

function generateDecode (name, fields, flagsPos, optionals) {
  const lines = []
  lines.push(`int`)
  lines.push(`${name}_decode (compact_state_t *state, ${name}_t *result)`)
  lines.push(`{`)
  lines.push(`  int err;`)

  for (let i = 0; i < fields.length; i++) {
    const field = fields[i]
    const cField = toCName(field.name)

    if (i === flagsPos) {
      lines.push(`  uintmax_t flags = 0;`)
      lines.push(`  if ((err = compact_decode_uint(state, &flags)) < 0) return err;`)
      for (let j = 0; j < optionals.length; j++) {
        lines.push(`  result->has_${toCName(optionals[j].name)} = (flags & (1u << ${j})) != 0;`)
      }
    }

    if (field.required) {
      lines.push(`  if ((err = compact_decode_uint(state, &result->${cField})) < 0) return err;`)
    } else {
      lines.push(`  if (result->has_${cField}) {`)
      lines.push(`    if ((err = compact_decode_uint(state, &result->${cField})) < 0) return err;`)
      lines.push(`  }`)
    }
  }

  lines.push(`  return 0;`)
  lines.push(`}`)
  return lines
}

function assertUintOnly (type) {
  for (const field of type.fields) {
    const base = resolveBase(field.type)
    if (base.name !== 'uint') {
      throw new Error(
        `hyperschema-c: unsupported field type "${base.name}" on ${type.fqn}.${field.name} — only uint is supported in v1`
      )
    }
  }
}

function resolveBase (type) {
  if (!type) throw new Error('hyperschema-c: field has no resolved type — schema may be incomplete')
  if (type.isAlias) return resolveBase(type.type)
  return type
}
